"""
Contineo Observe — SDK: timeline accessors.

Simple public functions for reading timeline data after a session runs.
"""

from __future__ import annotations

from contineo.sdk.state import state
from contineo.timeline.models import Timeline


def get_timeline(session_id: str) -> Timeline | None:
    """Return the execution timeline for a session.

    Args:
        session_id: The session ID generated by ``@contineo.observe``,
                    or the one you supplied to it.

    Returns:
        A ``Timeline`` with ``sorted_entries``, or ``None`` if the
        session has not been seen yet.

    Example::

        timeline = contineo.get_timeline(contineo.last_session_id())
        for entry in timeline.sorted_entries:
            print(entry.label, entry.duration_ms)
    """
    state.require_init()
    return state.timeline.get_timeline(session_id)


def last_session_id() -> str | None:
    """Return the session ID of the most recently started session.

    Useful in simple scripts where you don't want to track session IDs
    manually.

    Example::

        run("What is the weather in Tokyo?")
        timeline = contineo.get_timeline(contineo.last_session_id())
    """
    return state._last_session_id
