"""
Contineo Observe — SDK: timeline accessors.
"""

from __future__ import annotations

import asyncio

from contineo.sdk.state import state
from contineo.sdk.utils import fire
from contineo.timeline.models import Timeline


def get_timeline(session_id: str) -> Timeline | None:
    """Return the execution timeline for a session.

    Checks in-memory first. If not found and a storage backend is
    configured, loads from storage (e.g. from a previous process run).

    Args:
        session_id: The session ID generated by ``@contineo.observe``
                    or ``contineo.attach()``.

    Returns:
        A ``Timeline`` with ``sorted_entries``, or ``None`` if not found.
    """
    state.require_init()

    # Try in-memory first
    tl = state.timeline.get_timeline(session_id)
    if tl is not None:
        return tl

    # Fall back to storage
    if state.storage is not None:
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # Can't block — caller must use async path in async context
                return None
            return loop.run_until_complete(state.storage.get_timeline(session_id))
        except Exception:
            return None

    return None


def last_session_id() -> str | None:
    """Return the session ID of the most recently started session."""
    return state._last_session_id
